### PR TITLE
Refactor the code and drop lerna

### PR DESCRIPTION
**Pull request by Tanuj22**
Signed-off: Tanuj22 tanujagarwal22@gmail.com

### CODE REVIEW

**Comment by Tanuj22** [comment]
@leecalcote Please check this out. One question should I also drop the firebase deployment provided files provided by default?

**Comment by leecalcote** [comment]
@Tanuj22 yes, I think we can safely drop the firebase deployment. We can pull back out of the original template, if needed later, but intend to go with GitHub based deploy.

**Comment by leecalcote** [comment]
@Tanuj22 educate me, if you would. Why `npm` over `yarn`? Is `lerna` only valuable when using `nextjs`?

**Comment by Tanuj22** [comment]
@leecalcote `yarn` was used to create separate workspaces (`common`, `next-landing` and `gatsby-landing`) so that dependencies can be installed together for all the workspaces and `lerna` was used to add some additional functionality on top of the workspaces. After the removal of `next-landing` there was no need for separate workspaces so `common` and `gatsby-landing` could be merged. `gatsby-landing` was using `npm` so after merging `yarn` was dropped.

**Comment by leecalcote** [comment]
Makes sense. Thank you, @Tanuj22.

**Pull request merged**
